[Ready for reveiw] Polish-translation
w3c/wai-intro-uaag pull request #13
Opened 2024-03-07 18:18 UTC by zwiastunsw

I added polish.md.pl

2024-03-16 11:39 UTC, jcabak approved these changes

2024-03-16 11:39 UTC, jcabak commented on index.pl.md
> + i liście mejlingowej [WAI Interest Group](/about/groups/waiig/). Adres e-mail do wysyłania komentarzy znajduje się w&nbsp;sekcji [Status dokumentu](https://www.w3.org/TR/UAAG20/#status) UAAG 2.0.
mejlingowej ->mailingowej

2024-03-16 15:20 UTC, zwiastunsw commented on index.pl.md
> + i liście mejlingowej [WAI Interest Group](/about/groups/waiig/). Adres e-mail do wysyłania komentarzy znajduje się w&nbsp;sekcji [Status dokumentu](https://www.w3.org/TR/UAAG20/#status) UAAG 2.0.
It's Ok.

2024-04-29 08:03 UTC, remibetin requested changes
@zwiastunsw I have spotted a little issue. When fixed, I will be able to publish the translation: thanks very much!

2024-04-29 12:43 UTC, remibetin approved these changes

2024-04-29 17:18 UTC, merged